// ═══════════════════════════════════════════════════
// SEVEN FALLS — Bible Verse Database (gameplay codex)
// Auto-generated: 193 verses, 5 categories, cross-refs + combos.
// ═══════════════════════════════════════════════════

const BIBLE_VERSES = [
  {
    id:'ps23_1',
    text:'The LORD is my shepherd; I shall not want.',
    reference:'Psalm 23:1',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:10,
    effect:'damage',
    difficulty:1,
    crossRefs:['ps23_2', 'ps23_3', 'ps23_5', 'ps23_6', 'ps23_4'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Shepherd\'s first word: lack nothing.',
  },
  {
    id:'ps23_2',
    text:'He maketh me lie down in green pastures.',
    reference:'Psalm 23:2',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:9,
    effect:'damage',
    difficulty:1,
    crossRefs:['ps23_1', 'ps23_3', 'ps23_5', 'ps23_6', 'ps23_4'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps23_3',
    text:'He restoreth my soul: he leadeth me.',
    reference:'Psalm 23:3',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:9,
    effect:'heal_5',
    difficulty:1,
    crossRefs:['ps23_1', 'ps23_2', 'ps23_5', 'ps23_6', 'ps23_4'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps23_5',
    text:'Thou preparest a table before me.',
    reference:'Psalm 23:5',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:11,
    effect:'buff',
    difficulty:1,
    crossRefs:['ps23_1', 'ps23_2', 'ps23_3', 'ps23_6', 'ps23_4'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps23_6',
    text:'Surely goodness and mercy follow me.',
    reference:'Psalm 23:6',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:12,
    effect:'heal_5',
    difficulty:1,
    crossRefs:['ps23_1', 'ps23_2', 'ps23_3', 'ps23_5', 'ps23_4'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps27_1',
    text:'The LORD is my light and my salvation.',
    reference:'Psalm 27:1',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:14,
    effect:'damage',
    difficulty:1,
    crossRefs:['ps28_7', 'ps30_4'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps46_1',
    text:'God is our refuge and strength.',
    reference:'Psalm 46:1',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:12,
    effect:'damage',
    difficulty:1,
    crossRefs:['ps46_2', 'ps46_3'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps91_1',
    text:'He that dwelleth in the secret place.',
    reference:'Psalm 91:1',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:13,
    effect:'damage',
    difficulty:2,
    crossRefs:['ps91_2', 'ps91_3', 'ps91_4', 'ps91_5', 'ps91_6', 'ps91_11', 'ps91_12'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps91_2',
    text:'I will say, He is my refuge.',
    reference:'Psalm 91:2',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:11,
    effect:'damage',
    difficulty:2,
    crossRefs:['ps91_1', 'ps91_3', 'ps91_4', 'ps91_5', 'ps91_6', 'ps91_11', 'ps91_12'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps118_24',
    text:'This is the day the LORD hath made.',
    reference:'Psalm 118:24',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:9,
    effect:'damage',
    difficulty:1,
    crossRefs:['ps119_104', 'ps121_7'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps18_2',
    text:'The LORD is my rock and my fortress.',
    reference:'Psalm 18:2',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:13,
    effect:'damage',
    difficulty:2,
    crossRefs:['ps18_3', 'ps18_46', 'ps18_47', 'ps18_48', 'ps18_49'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps18_3',
    text:'I will call upon the LORD: saved.',
    reference:'Psalm 18:3',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:11,
    effect:'heal_5',
    difficulty:2,
    crossRefs:['ps18_2', 'ps18_46', 'ps18_47', 'ps18_48', 'ps18_49'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps34_7',
    text:'The angel of the LORD encampeth round.',
    reference:'Psalm 34:7',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:15,
    effect:'shield',
    difficulty:2,
    crossRefs:['ps34_17', 'ps34_18', 'ps34_19', 'ps34_20', 'ps34_8'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps121_7',
    text:'The LORD shall preserve thee from evil.',
    reference:'Psalm 121:7',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:12,
    effect:'damage',
    difficulty:2,
    crossRefs:['ps121_8', 'ps121_1', 'ps121_2'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps3_3',
    text:'Thou, O LORD, art a shield about me.',
    reference:'Psalm 3:3',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:12,
    effect:'damage',
    difficulty:1,
    crossRefs:['ps18_2', 'ps18_3'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps34_17',
    text:'The righteous cry, and the LORD heareth.',
    reference:'Psalm 34:17',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:10,
    effect:'heal_5',
    difficulty:2,
    crossRefs:['ps34_7', 'ps34_18', 'ps34_19', 'ps34_20', 'ps34_8'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps34_18',
    text:'The LORD is nigh the brokenhearted.',
    reference:'Psalm 34:18',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:10,
    effect:'heal_5',
    difficulty:2,
    crossRefs:['ps34_7', 'ps34_17', 'ps34_19', 'ps34_20', 'ps34_8'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps34_19',
    text:'Many are the afflictions of the righteous.',
    reference:'Psalm 34:19',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:9,
    effect:'damage',
    difficulty:2,
    crossRefs:['ps34_7', 'ps34_17', 'ps34_18', 'ps34_20', 'ps34_8'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps34_20',
    text:'He keepeth all his bones: none broken.',
    reference:'Psalm 34:20',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:11,
    effect:'shield',
    difficulty:2,
    crossRefs:['ps34_7', 'ps34_17', 'ps34_18', 'ps34_19', 'ps34_8'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps55_22',
    text:'Cast thy burden upon the LORD.',
    reference:'Psalm 55:22',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:12,
    effect:'heal_5',
    difficulty:2,
    crossRefs:['ps56_3', 'ps56_4'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps56_3',
    text:'When I am afraid, I will trust.',
    reference:'Psalm 56:3',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:11,
    effect:'shield',
    difficulty:2,
    crossRefs:['ps56_4', 'ps56_11'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps56_4',
    text:'In God I will praise his word.',
    reference:'Psalm 56:4',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:12,
    effect:'damage',
    difficulty:2,
    crossRefs:['ps56_3', 'ps56_11'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps139_7',
    text:'Whither shall I go from thy spirit?',
    reference:'Psalm 139:7',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:12,
    effect:'damage',
    difficulty:3,
    crossRefs:['ps139_8', 'ps139_9', 'ps139_10', 'ps139_11', 'ps139_12'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps139_8',
    text:'If I ascend to heaven, thou art there.',
    reference:'Psalm 139:8',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:11,
    effect:'damage',
    difficulty:3,
    crossRefs:['ps139_7', 'ps139_9', 'ps139_10', 'ps139_11', 'ps139_12'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps139_9',
    text:'If I take the wings of the morning.',
    reference:'Psalm 139:9',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:10,
    effect:'damage',
    difficulty:3,
    crossRefs:['ps139_7', 'ps139_8', 'ps139_10', 'ps139_11', 'ps139_12'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps139_10',
    text:'Even there shall thy hand lead me.',
    reference:'Psalm 139:10',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:11,
    effect:'buff',
    difficulty:3,
    crossRefs:['ps139_7', 'ps139_8', 'ps139_9', 'ps139_11', 'ps139_12'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps139_11',
    text:'If I say, Surely the darkness covers.',
    reference:'Psalm 139:11',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:11,
    effect:'debuff',
    difficulty:3,
    crossRefs:['ps139_7', 'ps139_8', 'ps139_9', 'ps139_10', 'ps139_12'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps139_12',
    text:'The darkness and the light are alike.',
    reference:'Psalm 139:12',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:11,
    effect:'debuff',
    difficulty:3,
    crossRefs:['ps139_7', 'ps139_8', 'ps139_9', 'ps139_10', 'ps139_11'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps18_46',
    text:'The LORD liveth; blessed be my rock.',
    reference:'Psalm 18:46',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:12,
    effect:'damage',
    difficulty:3,
    crossRefs:['ps18_2', 'ps18_3', 'ps18_47', 'ps18_48', 'ps18_49'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps18_47',
    text:'It is God that avengeth me.',
    reference:'Psalm 18:47',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:13,
    effect:'damage',
    difficulty:3,
    crossRefs:['ps18_2', 'ps18_3', 'ps18_46', 'ps18_48', 'ps18_49'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps18_48',
    text:'Thou liftest me above mine enemies.',
    reference:'Psalm 18:48',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:12,
    effect:'damage',
    difficulty:3,
    crossRefs:['ps18_2', 'ps18_3', 'ps18_46', 'ps18_47', 'ps18_49'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps18_49',
    text:'I will give thanks among the heathen.',
    reference:'Psalm 18:49',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:11,
    effect:'buff',
    difficulty:3,
    crossRefs:['ps18_2', 'ps18_3', 'ps18_46', 'ps18_47', 'ps18_48'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps20_6',
    text:'We will rejoice in thy salvation.',
    reference:'Psalm 20:6',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:12,
    effect:'heal_5',
    difficulty:2,
    crossRefs:['ps20_7'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps20_7',
    text:'Some trust in chariots: we in the LORD.',
    reference:'Psalm 20:7',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:11,
    effect:'damage',
    difficulty:2,
    crossRefs:['ps20_6'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps30_4',
    text:'Sing unto the LORD, O ye saints.',
    reference:'Psalm 30:4',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:12,
    effect:'buff',
    difficulty:2,
    crossRefs:['ps30_5'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps30_5',
    text:'Weeping may endure for a night.',
    reference:'Psalm 30:5',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:12,
    effect:'heal_5',
    difficulty:2,
    crossRefs:['ps30_4'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps47_5',
    text:'God is gone up with a shout.',
    reference:'Psalm 47:5',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:12,
    effect:'damage',
    difficulty:2,
    crossRefs:['ps47_6', 'ps47_7'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps47_6',
    text:'Sing praises to our King.',
    reference:'Psalm 47:6',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:11,
    effect:'buff',
    difficulty:2,
    crossRefs:['ps47_5', 'ps47_7'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps47_7',
    text:'God is the King of all the earth.',
    reference:'Psalm 47:7',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:11,
    effect:'damage',
    difficulty:2,
    crossRefs:['ps47_5', 'ps47_6'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps68_1',
    text:'Let God arise; let enemies scatter.',
    reference:'Psalm 68:1',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:12,
    effect:'damage',
    difficulty:2,
    crossRefs:['ps68_2'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps68_2',
    text:'As smoke is driven, drive them.',
    reference:'Psalm 68:2',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:12,
    effect:'damage',
    difficulty:2,
    crossRefs:['ps68_1'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps144_1',
    text:'Blessed be the LORD my strength.',
    reference:'Psalm 144:1',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:12,
    effect:'buff',
    difficulty:3,
    crossRefs:['ps144_2'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps144_2',
    text:'My fortress and my high tower.',
    reference:'Psalm 144:2',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:11,
    effect:'shield',
    difficulty:3,
    crossRefs:['ps144_1'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps145_18',
    text:'The LORD is nigh to all that call.',
    reference:'Psalm 145:18',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:12,
    effect:'heal_5',
    difficulty:3,
    crossRefs:['ps145_19'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps145_19',
    text:'He fulfils the desire of them that fear.',
    reference:'Psalm 145:19',
    book:'Psalms',
    category:'attack',
    verseType:'praise',
    damage:11,
    effect:'heal_5',
    difficulty:3,
    crossRefs:['ps145_18'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'rev12_11',
    text:'They overcame him by the blood of the Lamb.',
    reference:'Revelation 12:11',
    book:'Revelation',
    category:'attack',
    verseType:'fire',
    damage:16,
    effect:'damage',
    difficulty:2,
    crossRefs:['rev11_15', 'rev19_11'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'rev19_11',
    text:'Behold a white horse: he sat faithful.',
    reference:'Revelation 19:11',
    book:'Revelation',
    category:'attack',
    verseType:'fire',
    damage:18,
    effect:'damage',
    difficulty:3,
    crossRefs:['rev19_12', 'rev19_13', 'rev19_14', 'rev19_15', 'rev19_16'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'rev19_12',
    text:'His eyes were as a flame of fire.',
    reference:'Revelation 19:12',
    book:'Revelation',
    category:'attack',
    verseType:'fire',
    damage:17,
    effect:'damage',
    difficulty:3,
    crossRefs:['rev19_11', 'rev19_13', 'rev19_14', 'rev19_15', 'rev19_16'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'rev19_13',
    text:'Clothed with a vesture dipped in blood.',
    reference:'Revelation 19:13',
    book:'Revelation',
    category:'attack',
    verseType:'fire',
    damage:16,
    effect:'damage',
    difficulty:3,
    crossRefs:['rev19_11', 'rev19_12', 'rev19_14', 'rev19_15', 'rev19_16'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'rev19_14',
    text:'The armies in heaven followed him.',
    reference:'Revelation 19:14',
    book:'Revelation',
    category:'attack',
    verseType:'fire',
    damage:15,
    effect:'aoe',
    difficulty:3,
    crossRefs:['rev19_11', 'rev19_12', 'rev19_13', 'rev19_15', 'rev19_16'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'rev19_15',
    text:'Out of his mouth goeth a sharp sword.',
    reference:'Revelation 19:15',
    book:'Revelation',
    category:'attack',
    verseType:'fire',
    damage:25,
    effect:'damage',
    difficulty:3,
    crossRefs:['rev19_11', 'rev19_12', 'rev19_13', 'rev19_14', 'rev19_16'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'rev19_16',
    text:'King of Kings, and Lord of Lords.',
    reference:'Revelation 19:16',
    book:'Revelation',
    category:'attack',
    verseType:'fire',
    damage:20,
    effect:'damage',
    difficulty:3,
    crossRefs:['rev19_11', 'rev19_12', 'rev19_13', 'rev19_14', 'rev19_15'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'rev21_4',
    text:'God shall wipe away all tears.',
    reference:'Revelation 21:4',
    book:'Revelation',
    category:'attack',
    verseType:'fire',
    damage:14,
    effect:'heal_15',
    difficulty:2,
    crossRefs:['rev20_10', 'rev22_20'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'rev3_20',
    text:'Behold, I stand at the door and knock.',
    reference:'Revelation 3:20',
    book:'Revelation',
    category:'attack',
    verseType:'fire',
    damage:12,
    effect:'heal_5',
    difficulty:2,
    crossRefs:['rev3_19'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'rev20_10',
    text:'The devil cast into the lake of fire.',
    reference:'Revelation 20:10',
    book:'Revelation',
    category:'attack',
    verseType:'fire',
    damage:18,
    effect:'execute',
    difficulty:3,
    crossRefs:['rev19_11', 'rev19_12'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'rev2_10',
    text:'Be faithful unto death: I give a crown.',
    reference:'Revelation 2:10',
    book:'Revelation',
    category:'attack',
    verseType:'fire',
    damage:15,
    effect:'buff',
    difficulty:2,
    crossRefs:['rev3_20', 'rev1_17'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'rev1_17',
    text:'I am the first and the last.',
    reference:'Revelation 1:17',
    book:'Revelation',
    category:'attack',
    verseType:'fire',
    damage:13,
    effect:'damage',
    difficulty:3,
    crossRefs:['rev1_18', 'rev1_8'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'rev1_18',
    text:'I have the keys of hell and death.',
    reference:'Revelation 1:18',
    book:'Revelation',
    category:'attack',
    verseType:'fire',
    damage:13,
    effect:'damage',
    difficulty:3,
    crossRefs:['rev1_17', 'rev1_8'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'rev22_20',
    text:'Surely I come quickly. Amen.',
    reference:'Revelation 22:20',
    book:'Revelation',
    category:'attack',
    verseType:'fire',
    damage:12,
    effect:'buff',
    difficulty:2,
    crossRefs:['rev22_13'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'isa41_10',
    text:'Fear thou not; I am with thee.',
    reference:'Isaiah 41:10',
    book:'Isaiah',
    category:'attack',
    verseType:'warfare',
    damage:16,
    effect:'damage',
    difficulty:1,
    crossRefs:['isa40_31', 'isa40_28'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'isa40_31',
    text:'They that wait renew their strength.',
    reference:'Isaiah 40:31',
    book:'Isaiah',
    category:'attack',
    verseType:'warfare',
    damage:17,
    effect:'buff',
    difficulty:1,
    crossRefs:['isa40_28'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'isa59_19',
    text:'The Spirit lifteth up a standard.',
    reference:'Isaiah 59:19',
    book:'Isaiah',
    category:'attack',
    verseType:'warfare',
    damage:16,
    effect:'damage',
    difficulty:3,
    crossRefs:['isa54_17', 'isa46_4'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'isa26_3',
    text:'Thou keepest him in perfect peace.',
    reference:'Isaiah 26:3',
    book:'Isaiah',
    category:'attack',
    verseType:'warfare',
    damage:13,
    effect:'shield',
    difficulty:2,
    crossRefs:['isa30_15', 'isa40_31'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'isa30_15',
    text:'In returning and rest ye are saved.',
    reference:'Isaiah 30:15',
    book:'Isaiah',
    category:'attack',
    verseType:'warfare',
    damage:12,
    effect:'heal_5',
    difficulty:2,
    crossRefs:['isa26_3', 'isa40_31'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'jos1_9',
    text:'Be strong and of good courage.',
    reference:'Joshua 1:9',
    book:'Joshua',
    category:'attack',
    verseType:'warfare',
    damage:15,
    effect:'damage',
    difficulty:1,
    crossRefs:['eph6_10', 'phil4_13'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'Courage is a command.',
  },
  {
    id:'dan6_22',
    text:'My God sent his angel, delivered me.',
    reference:'Daniel 6:22',
    book:'Daniel',
    category:'attack',
    verseType:'warfare',
    damage:16,
    effect:'heal_10',
    difficulty:2,
    crossRefs:['dan6_23'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The lions\' mouths were shut.',
  },
  {
    id:'dan6_23',
    text:'No manner of hurt was found on him.',
    reference:'Daniel 6:23',
    book:'Daniel',
    category:'attack',
    verseType:'warfare',
    damage:14,
    effect:'shield',
    difficulty:2,
    crossRefs:['dan6_22'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Word strikes like a flame.',
  },
  {
    id:'ps23_4',
    text:'Yea, though I walk, I fear no evil.',
    reference:'Psalm 23:4',
    book:'Psalms',
    category:'defense',
    verseType:'praise',
    damage:0,
    effect:'shield',
    difficulty:1,
    crossRefs:['ps23_1', 'ps23_2', 'ps23_3', 'ps23_5', 'ps23_6'],
    comboWith:['ps23_1', 'ps23_2'],
    desc:'The Word is shield and refuge.',
  },
  {
    id:'ps46_2',
    text:'A very present help in trouble.',
    reference:'Psalm 46:2',
    book:'Psalms',
    category:'defense',
    verseType:'praise',
    damage:0,
    effect:'shield',
    difficulty:1,
    crossRefs:['ps46_1', 'ps46_3'],
    comboWith:['ps23_1', 'ps23_2'],
    desc:'The Word is shield and refuge.',
  },
  {
    id:'ps91_3',
    text:'He shall deliver thee from the snare.',
    reference:'Psalm 91:3',
    book:'Psalms',
    category:'defense',
    verseType:'praise',
    damage:0,
    effect:'shield',
    difficulty:2,
    crossRefs:['ps91_1', 'ps91_2', 'ps91_4', 'ps91_5', 'ps91_6', 'ps91_11', 'ps91_12'],
    comboWith:['ps23_1', 'ps23_2'],
    desc:'The Word is shield and refuge.',
  },
  {
    id:'ps91_4',
    text:'With his feathers he covers thee.',
    reference:'Psalm 91:4',
    book:'Psalms',
    category:'defense',
    verseType:'praise',
    damage:0,
    effect:'shield',
    difficulty:1,
    crossRefs:['ps91_1', 'ps91_2', 'ps91_3', 'ps91_5', 'ps91_6', 'ps91_11', 'ps91_12'],
    comboWith:['ps23_1', 'ps23_2'],
    desc:'The Word is shield and refuge.',
  },
  {
    id:'ps121_8',
    text:'The LORD preserves thy going out.',
    reference:'Psalm 121:8',
    book:'Psalms',
    category:'defense',
    verseType:'praise',
    damage:0,
    effect:'shield',
    difficulty:2,
    crossRefs:['ps121_7', 'ps121_1', 'ps121_2'],
    comboWith:['ps23_1', 'ps23_2'],
    desc:'The Word is shield and refuge.',
  },
  {
    id:'ps138_7',
    text:'Though I walk in trouble, thou savest.',
    reference:'Psalm 138:7',
    book:'Psalms',
    category:'defense',
    verseType:'praise',
    damage:0,
    effect:'shield',
    difficulty:2,
    crossRefs:['ps139_7', 'ps139_8'],
    comboWith:['ps23_1', 'ps23_2'],
    desc:'The Word is shield and refuge.',
  },
  {
    id:'ps62_1',
    text:'Truly my soul waiteth upon God.',
    reference:'Psalm 62:1',
    book:'Psalms',
    category:'defense',
    verseType:'praise',
    damage:0,
    effect:'shield',
    difficulty:2,
    crossRefs:['ps62_2'],
    comboWith:['ps23_1', 'ps23_2'],
    desc:'The Word is shield and refuge.',
  },
  {
    id:'ps62_2',
    text:'He only is my rock and salvation.',
    reference:'Psalm 62:2',
    book:'Psalms',
    category:'defense',
    verseType:'praise',
    damage:0,
    effect:'shield',
    difficulty:2,
    crossRefs:['ps62_1'],
    comboWith:['ps23_1', 'ps23_2'],
    desc:'The Word is shield and refuge.',
  },
  {
    id:'ps28_7',
    text:'The LORD is my strength and shield.',
    reference:'Psalm 28:7',
    book:'Psalms',
    category:'defense',
    verseType:'praise',
    damage:0,
    effect:'shield',
    difficulty:1,
    crossRefs:['ps27_1', 'ps30_4'],
    comboWith:['ps23_1', 'ps23_2'],
    desc:'The Word is shield and refuge.',
  },
  {
    id:'ps59_16',
    text:'In thee, O God, do I sing aloud.',
    reference:'Psalm 59:16',
    book:'Psalms',
    category:'defense',
    verseType:'praise',
    damage:0,
    effect:'heal_5',
    difficulty:2,
    crossRefs:['ps61_3', 'ps56_3'],
    comboWith:['ps23_1', 'ps23_2'],
    desc:'The Word is shield and refuge.',
  },
  {
    id:'ps91_5',
    text:'Thou shalt not fear the terror.',
    reference:'Psalm 91:5',
    book:'Psalms',
    category:'defense',
    verseType:'praise',
    damage:0,
    effect:'shield',
    difficulty:1,
    crossRefs:['ps91_1', 'ps91_2', 'ps91_3', 'ps91_4', 'ps91_6', 'ps91_11', 'ps91_12'],
    comboWith:['ps23_1', 'ps23_2'],
    desc:'The Word is shield and refuge.',
  },
  {
    id:'ps91_6',
    text:'Nor the arrow that flieth by day.',
    reference:'Psalm 91:6',
    book:'Psalms',
    category:'defense',
    verseType:'praise',
    damage:0,
    effect:'shield',
    difficulty:2,
    crossRefs:['ps91_1', 'ps91_2', 'ps91_3', 'ps91_4', 'ps91_5', 'ps91_11', 'ps91_12'],
    comboWith:['ps23_1', 'ps23_2'],
    desc:'The Word is shield and refuge.',
  },
  {
    id:'ps121_1',
    text:'I lift up mine eyes to the hills.',
    reference:'Psalm 121:1',
    book:'Psalms',
    category:'defense',
    verseType:'praise',
    damage:0,
    effect:'shield',
    difficulty:1,
    crossRefs:['ps121_7', 'ps121_8', 'ps121_2'],
    comboWith:['ps23_1', 'ps23_2'],
    desc:'The Word is shield and refuge.',
  },
  {
    id:'ps121_2',
    text:'My help cometh from the LORD.',
    reference:'Psalm 121:2',
    book:'Psalms',
    category:'defense',
    verseType:'praise',
    damage:0,
    effect:'shield',
    difficulty:1,
    crossRefs:['ps121_7', 'ps121_8', 'ps121_1'],
    comboWith:['ps23_1', 'ps23_2'],
    desc:'The Word is shield and refuge.',
  },
  {
    id:'ps46_3',
    text:'God is in the midst of her.',
    reference:'Psalm 46:3',
    book:'Psalms',
    category:'defense',
    verseType:'praise',
    damage:0,
    effect:'shield',
    difficulty:2,
    crossRefs:['ps46_1', 'ps46_2'],
    comboWith:['ps23_1', 'ps23_2'],
    desc:'The Word is shield and refuge.',
  },
  {
    id:'ps34_8',
    text:'O taste and see the LORD is good.',
    reference:'Psalm 34:8',
    book:'Psalms',
    category:'defense',
    verseType:'praise',
    damage:0,
    effect:'heal_5',
    difficulty:1,
    crossRefs:['ps34_7', 'ps34_17', 'ps34_18', 'ps34_19', 'ps34_20'],
    comboWith:['ps23_1', 'ps23_2'],
    desc:'The Word is shield and refuge.',
  },
  {
    id:'ps37_39',
    text:'Salvation of the righteous is of LORD.',
    reference:'Psalm 37:39',
    book:'Psalms',
    category:'defense',
    verseType:'praise',
    damage:0,
    effect:'shield',
    difficulty:2,
    crossRefs:['ps34_7', 'ps34_17'],
    comboWith:['ps23_1', 'ps23_2'],
    desc:'The Word is shield and refuge.',
  },
  {
    id:'ps56_11',
    text:'In God have I put my trust.',
    reference:'Psalm 56:11',
    book:'Psalms',
    category:'defense',
    verseType:'praise',
    damage:0,
    effect:'shield',
    difficulty:1,
    crossRefs:['ps56_3', 'ps56_4'],
    comboWith:['ps23_1', 'ps23_2'],
    desc:'The Word is shield and refuge.',
  },
  {
    id:'ps61_3',
    text:'Thou hast been a shelter for me.',
    reference:'Psalm 61:3',
    book:'Psalms',
    category:'defense',
    verseType:'praise',
    damage:0,
    effect:'shield',
    difficulty:2,
    crossRefs:['ps62_1', 'ps62_2'],
    comboWith:['ps23_1', 'ps23_2'],
    desc:'The Word is shield and refuge.',
  },
  {
    id:'ps63_7',
    text:'In the shadow of thy wings rejoice.',
    reference:'Psalm 63:7',
    book:'Psalms',
    category:'defense',
    verseType:'praise',
    damage:0,
    effect:'shield',
    difficulty:2,
    crossRefs:['ps62_1', 'ps62_2'],
    comboWith:['ps23_1', 'ps23_2'],
    desc:'The Word is shield and refuge.',
  },
  {
    id:'ps125_1',
    text:'They that trust in the LORD are mount.',
    reference:'Psalm 125:1',
    book:'Psalms',
    category:'defense',
    verseType:'praise',
    damage:0,
    effect:'shield',
    difficulty:1,
    crossRefs:['ps121_7', 'ps121_8'],
    comboWith:['ps23_1', 'ps23_2'],
    desc:'The Word is shield and refuge.',
  },
  {
    id:'ps115_9',
    text:'O Israel, trust in the LORD.',
    reference:'Psalm 115:9',
    book:'Psalms',
    category:'defense',
    verseType:'praise',
    damage:0,
    effect:'shield',
    difficulty:2,
    crossRefs:['ps118_24', 'ps119_104'],
    comboWith:['ps23_1', 'ps23_2'],
    desc:'The Word is shield and refuge.',
  },
  {
    id:'eph6_11',
    text:'Put on the whole armour of God.',
    reference:'Ephesians 6:11',
    book:'Ephesians',
    category:'defense',
    verseType:'warfare',
    damage:0,
    effect:'armor',
    difficulty:1,
    crossRefs:['eph6_12', 'eph6_13', 'eph6_14', 'eph6_15', 'eph6_16', 'eph6_17', 'eph6_18', 'eph6_10'],
    comboWith:['ps23_1', 'ps23_2'],
    desc:'The Word is shield and refuge.',
  },
  {
    id:'eph6_12',
    text:'We wrestle not against flesh and blood.',
    reference:'Ephesians 6:12',
    book:'Ephesians',
    category:'defense',
    verseType:'warfare',
    damage:0,
    effect:'debuff',
    difficulty:2,
    crossRefs:['eph6_11', 'eph6_13', 'eph6_14', 'eph6_15', 'eph6_16', 'eph6_17', 'eph6_18', 'eph6_10'],
    comboWith:['ps23_1', 'ps23_2'],
    desc:'The Word is shield and refuge.',
  },
  {
    id:'eph6_13',
    text:'Take the armour, withstand the evil.',
    reference:'Ephesians 6:13',
    book:'Ephesians',
    category:'defense',
    verseType:'warfare',
    damage:0,
    effect:'armor',
    difficulty:2,
    crossRefs:['eph6_11', 'eph6_12', 'eph6_14', 'eph6_15', 'eph6_16', 'eph6_17', 'eph6_18', 'eph6_10'],
    comboWith:['ps23_1', 'ps23_2'],
    desc:'The Word is shield and refuge.',
  },
  {
    id:'eph6_14',
    text:'Stand with loins girt with truth.',
    reference:'Ephesians 6:14',
    book:'Ephesians',
    category:'defense',
    verseType:'warfare',
    damage:0,
    effect:'armor',
    difficulty:2,
    crossRefs:['eph6_11', 'eph6_12', 'eph6_13', 'eph6_15', 'eph6_16', 'eph6_17', 'eph6_18', 'eph6_10'],
    comboWith:['ps23_1', 'ps23_2'],
    desc:'The Word is shield and refuge.',
  },
  {
    id:'eph6_15',
    text:'Shod with gospel of peace.',
    reference:'Ephesians 6:15',
    book:'Ephesians',
    category:'defense',
    verseType:'warfare',
    damage:0,
    effect:'armor',
    difficulty:2,
    crossRefs:['eph6_11', 'eph6_12', 'eph6_13', 'eph6_14', 'eph6_16', 'eph6_17', 'eph6_18', 'eph6_10'],
    comboWith:['ps23_1', 'ps23_2'],
    desc:'The Word is shield and refuge.',
  },
  {
    id:'eph6_16',
    text:'Shield of faith quenches fiery darts.',
    reference:'Ephesians 6:16',
    book:'Ephesians',
    category:'defense',
    verseType:'warfare',
    damage:0,
    effect:'shield',
    difficulty:1,
    crossRefs:['eph6_11', 'eph6_12', 'eph6_13', 'eph6_14', 'eph6_15', 'eph6_17', 'eph6_18', 'eph6_10'],
    comboWith:['ps23_1', 'ps23_2'],
    desc:'The Word is shield and refuge.',
  },
  {
    id:'eph6_17',
    text:'Sword of the Spirit, word of God.',
    reference:'Ephesians 6:17',
    book:'Ephesians',
    category:'defense',
    verseType:'warfare',
    damage:0,
    effect:'damage',
    difficulty:1,
    crossRefs:['eph6_11', 'eph6_12', 'eph6_13', 'eph6_14', 'eph6_15', 'eph6_16', 'eph6_18', 'eph6_10'],
    comboWith:['ps23_1', 'ps23_2'],
    desc:'The Word is shield and refuge.',
  },
  {
    id:'eph6_18',
    text:'Praying always with all prayer.',
    reference:'Ephesians 6:18',
    book:'Ephesians',
    category:'defense',
    verseType:'warfare',
    damage:0,
    effect:'heal_5',
    difficulty:2,
    crossRefs:['eph6_11', 'eph6_12', 'eph6_13', 'eph6_14', 'eph6_15', 'eph6_16', 'eph6_17', 'eph6_10'],
    comboWith:['ps23_1', 'ps23_2'],
    desc:'The Word is shield and refuge.',
  },
  {
    id:'prov30_5',
    text:'Every word of God is pure.',
    reference:'Proverbs 30:5',
    book:'Proverbs',
    category:'defense',
    verseType:'wisdom',
    damage:0,
    effect:'shield',
    difficulty:1,
    crossRefs:['prov30_6'],
    comboWith:['ps23_1', 'ps23_2'],
    desc:'The Word is shield and refuge.',
  },
  {
    id:'prov30_6',
    text:'Add not to his words, lest reproved.',
    reference:'Proverbs 30:6',
    book:'Proverbs',
    category:'defense',
    verseType:'wisdom',
    damage:0,
    effect:'debuff',
    difficulty:2,
    crossRefs:['prov30_5'],
    comboWith:['ps23_1', 'ps23_2'],
    desc:'The Word is shield and refuge.',
  },
  {
    id:'pet1_5',
    text:'Kept by the power of God through faith.',
    reference:'1 Peter 1:5',
    book:'1 Peter',
    category:'defense',
    verseType:'mercy',
    damage:0,
    effect:'shield',
    difficulty:2,
    crossRefs:['pet1_7'],
    comboWith:['ps23_1', 'ps23_2'],
    desc:'The Word is shield and refuge.',
  },
  {
    id:'tim2_3',
    text:'Endure hardness, good soldier.',
    reference:'2 Timothy 2:3',
    book:'2 Timothy',
    category:'defense',
    verseType:'mercy',
    damage:0,
    effect:'armor',
    difficulty:2,
    crossRefs:['tim2_4', 'tim2_25'],
    comboWith:['ps23_1', 'ps23_2'],
    desc:'The Word is shield and refuge.',
  },
  {
    id:'tim2_4',
    text:'No soldier entangleth himself.',
    reference:'2 Timothy 2:4',
    book:'2 Timothy',
    category:'defense',
    verseType:'mercy',
    damage:0,
    effect:'armor',
    difficulty:2,
    crossRefs:['tim2_3', 'tim2_25'],
    comboWith:['ps23_1', 'ps23_2'],
    desc:'The Word is shield and refuge.',
  },
  {
    id:'prov3_5',
    text:'Trust in the LORD with all thine heart.',
    reference:'Proverbs 3:5',
    book:'Proverbs',
    category:'buff',
    verseType:'wisdom',
    damage:0,
    effect:'buff',
    difficulty:1,
    crossRefs:['prov3_6'],
    comboWith:['prov16_24', 'prov25_15'],
    desc:'Reason bows; trust leads.',
  },
  {
    id:'prov3_6',
    text:'In all thy ways acknowledge him.',
    reference:'Proverbs 3:6',
    book:'Proverbs',
    category:'buff',
    verseType:'wisdom',
    damage:0,
    effect:'buff',
    difficulty:1,
    crossRefs:['prov3_5'],
    comboWith:['prov16_24', 'prov25_15'],
    desc:'The Word strengthens the soul.',
  },
  {
    id:'prov9_10',
    text:'Fear of LORD is wisdom\'s beginning.',
    reference:'Proverbs 9:10',
    book:'Proverbs',
    category:'buff',
    verseType:'wisdom',
    damage:0,
    effect:'buff',
    difficulty:2,
    crossRefs:['prov11_21', 'prov6_16'],
    comboWith:['prov16_24', 'prov25_15'],
    desc:'The Word strengthens the soul.',
  },
  {
    id:'prov15_1',
    text:'A soft answer turneth away wrath.',
    reference:'Proverbs 15:1',
    book:'Proverbs',
    category:'buff',
    verseType:'wisdom',
    damage:0,
    effect:'buff',
    difficulty:1,
    crossRefs:['prov16_3', 'prov16_24'],
    comboWith:['prov16_24', 'prov25_15'],
    desc:'The Word strengthens the soul.',
  },
  {
    id:'prov18_21',
    text:'Death and life in the tongue\'s power.',
    reference:'Proverbs 18:21',
    book:'Proverbs',
    category:'buff',
    verseType:'wisdom',
    damage:0,
    effect:'buff',
    difficulty:2,
    crossRefs:['prov17_17', 'prov19_5'],
    comboWith:['prov16_24', 'prov25_15'],
    desc:'The Word strengthens the soul.',
  },
  {
    id:'prov24_16',
    text:'A just man falls seven times, rises.',
    reference:'Proverbs 24:16',
    book:'Proverbs',
    category:'buff',
    verseType:'wisdom',
    damage:0,
    effect:'buff',
    difficulty:3,
    crossRefs:['prov24_24'],
    comboWith:['prov16_24', 'prov25_15'],
    desc:'The Word strengthens the soul.',
  },
  {
    id:'prov2_6',
    text:'The LORD giveth wisdom.',
    reference:'Proverbs 2:6',
    book:'Proverbs',
    category:'buff',
    verseType:'wisdom',
    damage:0,
    effect:'buff',
    difficulty:2,
    crossRefs:['prov2_7', 'prov2_8'],
    comboWith:['prov16_24', 'prov25_15'],
    desc:'The Word strengthens the soul.',
  },
  {
    id:'prov2_7',
    text:'He lays up wisdom for the just.',
    reference:'Proverbs 2:7',
    book:'Proverbs',
    category:'buff',
    verseType:'wisdom',
    damage:0,
    effect:'buff',
    difficulty:3,
    crossRefs:['prov2_6', 'prov2_8'],
    comboWith:['prov16_24', 'prov25_15'],
    desc:'The Word strengthens the soul.',
  },
  {
    id:'prov2_8',
    text:'He keepeth the paths of judgment.',
    reference:'Proverbs 2:8',
    book:'Proverbs',
    category:'buff',
    verseType:'wisdom',
    damage:0,
    effect:'buff',
    difficulty:3,
    crossRefs:['prov2_6', 'prov2_7'],
    comboWith:['prov16_24', 'prov25_15'],
    desc:'The Word strengthens the soul.',
  },
  {
    id:'prov4_7',
    text:'Wisdom is the principal thing.',
    reference:'Proverbs 4:7',
    book:'Proverbs',
    category:'buff',
    verseType:'wisdom',
    damage:0,
    effect:'buff',
    difficulty:2,
    crossRefs:['prov4_8'],
    comboWith:['prov16_24', 'prov25_15'],
    desc:'The Word strengthens the soul.',
  },
  {
    id:'prov4_8',
    text:'Exalt her, she brings honour.',
    reference:'Proverbs 4:8',
    book:'Proverbs',
    category:'buff',
    verseType:'wisdom',
    damage:0,
    effect:'buff',
    difficulty:3,
    crossRefs:['prov4_7'],
    comboWith:['prov16_24', 'prov25_15'],
    desc:'The Word strengthens the soul.',
  },
  {
    id:'prov16_3',
    text:'Roll thy works upon the LORD.',
    reference:'Proverbs 16:3',
    book:'Proverbs',
    category:'buff',
    verseType:'wisdom',
    damage:0,
    effect:'buff',
    difficulty:1,
    crossRefs:['prov16_24', 'prov16_5'],
    comboWith:['prov16_24', 'prov25_15'],
    desc:'The Word strengthens the soul.',
  },
  {
    id:'prov17_17',
    text:'A friend loveth at all times.',
    reference:'Proverbs 17:17',
    book:'Proverbs',
    category:'buff',
    verseType:'wisdom',
    damage:0,
    effect:'buff',
    difficulty:1,
    crossRefs:['prov18_21', 'prov16_3'],
    comboWith:['prov16_24', 'prov25_15'],
    desc:'The Word strengthens the soul.',
  },
  {
    id:'prov27_17',
    text:'Iron sharpeneth iron.',
    reference:'Proverbs 27:17',
    book:'Proverbs',
    category:'buff',
    verseType:'wisdom',
    damage:0,
    effect:'buff',
    difficulty:1,
    crossRefs:['prov26_24', 'prov26_25'],
    comboWith:['prov16_24', 'prov25_15'],
    desc:'The Word strengthens the soul.',
  },
  {
    id:'phil4_19',
    text:'My God shall supply all your need.',
    reference:'Philippians 4:19',
    book:'Philippians',
    category:'buff',
    verseType:'mercy',
    damage:0,
    effect:'buff',
    difficulty:2,
    crossRefs:['phil4_13'],
    comboWith:['prov16_24', 'prov25_15'],
    desc:'The Word strengthens the soul.',
  },
  {
    id:'rom8_28',
    text:'All things work for good.',
    reference:'Romans 8:28',
    book:'Romans',
    category:'buff',
    verseType:'mercy',
    damage:0,
    effect:'buff',
    difficulty:1,
    crossRefs:['rom8_37', 'rom8_38', 'rom8_39', 'rom8_31'],
    comboWith:['prov16_24', 'prov25_15'],
    desc:'The Word strengthens the soul.',
  },
  {
    id:'rom8_37',
    text:'We are more than conquerors.',
    reference:'Romans 8:37',
    book:'Romans',
    category:'buff',
    verseType:'mercy',
    damage:0,
    effect:'buff',
    difficulty:2,
    crossRefs:['rom8_28', 'rom8_38', 'rom8_39', 'rom8_31'],
    comboWith:['prov16_24', 'prov25_15'],
    desc:'The Word strengthens the soul.',
  },
  {
    id:'rom8_38',
    text:'Nor death, nor life, separates.',
    reference:'Romans 8:38',
    book:'Romans',
    category:'buff',
    verseType:'mercy',
    damage:0,
    effect:'buff',
    difficulty:3,
    crossRefs:['rom8_28', 'rom8_37', 'rom8_39', 'rom8_31'],
    comboWith:['prov16_24', 'prov25_15'],
    desc:'The Word strengthens the soul.',
  },
  {
    id:'rom8_39',
    text:'Nor any creature from God\'s love.',
    reference:'Romans 8:39',
    book:'Romans',
    category:'buff',
    verseType:'mercy',
    damage:0,
    effect:'buff',
    difficulty:3,
    crossRefs:['rom8_28', 'rom8_37', 'rom8_38', 'rom8_31'],
    comboWith:['prov16_24', 'prov25_15'],
    desc:'The Word strengthens the soul.',
  },
  {
    id:'cor1_10_13',
    text:'God is faithful; no temptation too great.',
    reference:'1 Corinthians 10:13',
    book:'1 Corinthians',
    category:'buff',
    verseType:'mercy',
    damage:0,
    effect:'buff',
    difficulty:2,
    crossRefs:['cor1_15_57'],
    comboWith:['prov16_24', 'prov25_15'],
    desc:'The Word strengthens the soul.',
  },
  {
    id:'cor2_12_10',
    text:'When weak, then am I strong.',
    reference:'2 Corinthians 12:10',
    book:'2 Corinthians',
    category:'buff',
    verseType:'mercy',
    damage:0,
    effect:'buff',
    difficulty:2,
    crossRefs:['cor2_12_9'],
    comboWith:['cor2_10_4', 'cor2_10_5'],
    desc:'The Word strengthens the soul.',
  },
  {
    id:'cor1_15_57',
    text:'Thanks be to God, gives victory.',
    reference:'1 Corinthians 15:57',
    book:'1 Corinthians',
    category:'buff',
    verseType:'mercy',
    damage:0,
    effect:'buff',
    difficulty:1,
    crossRefs:['cor1_10_13'],
    comboWith:['prov16_24', 'prov25_15'],
    desc:'The Word strengthens the soul.',
  },
  {
    id:'phil2_13',
    text:'God worketh in you to will.',
    reference:'Philippians 2:13',
    book:'Philippians',
    category:'buff',
    verseType:'mercy',
    damage:0,
    effect:'buff',
    difficulty:2,
    crossRefs:['phil3_14', 'phil1_6'],
    comboWith:['prov16_24', 'prov25_15'],
    desc:'The Word strengthens the soul.',
  },
  {
    id:'phil3_14',
    text:'Press toward the high calling.',
    reference:'Philippians 3:14',
    book:'Philippians',
    category:'buff',
    verseType:'mercy',
    damage:0,
    effect:'buff',
    difficulty:2,
    crossRefs:['phil4_19', 'phil2_13'],
    comboWith:['prov16_24', 'prov25_15'],
    desc:'The Word strengthens the soul.',
  },
  {
    id:'phil1_6',
    text:'He will finish the good work.',
    reference:'Philippians 1:6',
    book:'Philippians',
    category:'buff',
    verseType:'mercy',
    damage:0,
    effect:'buff',
    difficulty:1,
    crossRefs:['phil2_13', 'phil3_14'],
    comboWith:['prov16_24', 'prov25_15'],
    desc:'The Word strengthens the soul.',
  },
  {
    id:'rom12_2',
    text:'Be not conformed, but transformed.',
    reference:'Romans 12:2',
    book:'Romans',
    category:'buff',
    verseType:'mercy',
    damage:0,
    effect:'buff',
    difficulty:2,
    crossRefs:['rom15_13', 'rom8_28'],
    comboWith:['prov16_24', 'prov25_15'],
    desc:'The Word strengthens the soul.',
  },
  {
    id:'rom15_13',
    text:'God of hope fills you with joy.',
    reference:'Romans 15:13',
    book:'Romans',
    category:'buff',
    verseType:'mercy',
    damage:0,
    effect:'buff',
    difficulty:1,
    crossRefs:['rom16_20', 'rom12_2'],
    comboWith:['prov16_24', 'prov25_15'],
    desc:'The Word strengthens the soul.',
  },
  {
    id:'tim1_7',
    text:'God gave a spirit of power, love.',
    reference:'2 Timothy 1:7',
    book:'2 Timothy',
    category:'buff',
    verseType:'mercy',
    damage:0,
    effect:'buff',
    difficulty:1,
    crossRefs:['tim2_3', 'tim2_4'],
    comboWith:['tim2_25', 'prov16_24'],
    desc:'The Word strengthens the soul.',
  },
  {
    id:'heb11_1',
    text:'Faith is substance of things hoped.',
    reference:'Hebrews 11:1',
    book:'Hebrews',
    category:'buff',
    verseType:'mercy',
    damage:0,
    effect:'buff',
    difficulty:2,
    crossRefs:['heb12_2', 'heb4_12'],
    comboWith:['heb4_12', 'prov16_24'],
    desc:'The Word strengthens the soul.',
  },
  {
    id:'jam1_5',
    text:'If any lack wisdom, let him ask.',
    reference:'James 1:5',
    book:'James',
    category:'buff',
    verseType:'mercy',
    damage:0,
    effect:'buff',
    difficulty:1,
    crossRefs:['jam4_7', 'jam5_16'],
    comboWith:['jam4_7', 'jam5_16'],
    desc:'The Word strengthens the soul.',
  },
  {
    id:'gal5_22',
    text:'Fruit of Spirit: love, joy, peace.',
    reference:'Galatians 5:22',
    book:'Galatians',
    category:'buff',
    verseType:'mercy',
    damage:0,
    effect:'buff',
    difficulty:2,
    crossRefs:['prov3_5', 'rom8_28'],
    comboWith:['prov16_24', 'prov25_15'],
    desc:'The Word strengthens the soul.',
  },
  {
    id:'prov16_24',
    text:'Pleasant words are as honeycomb.',
    reference:'Proverbs 16:24',
    book:'Proverbs',
    category:'debuff',
    verseType:'wisdom',
    damage:0,
    effect:'debuff',
    difficulty:2,
    crossRefs:['prov16_3', 'prov16_5'],
    comboWith:['prov3_5', 'prov3_6'],
    desc:'The Word binds the enemy.',
  },
  {
    id:'prov25_15',
    text:'Soft tongue breaketh the bone.',
    reference:'Proverbs 25:15',
    book:'Proverbs',
    category:'debuff',
    verseType:'wisdom',
    damage:0,
    effect:'debuff',
    difficulty:2,
    crossRefs:['prov24_16', 'prov26_24'],
    comboWith:['prov3_5', 'prov3_6'],
    desc:'The Word binds the enemy.',
  },
  {
    id:'prov26_24',
    text:'He that hateth dissembleth with lips.',
    reference:'Proverbs 26:24',
    book:'Proverbs',
    category:'debuff',
    verseType:'wisdom',
    damage:0,
    effect:'debuff',
    difficulty:3,
    crossRefs:['prov26_25', 'prov26_26', 'prov26_27'],
    comboWith:['prov3_5', 'prov3_6'],
    desc:'The Word binds the enemy.',
  },
  {
    id:'prov26_25',
    text:'His hatred is deceitfully hidden.',
    reference:'Proverbs 26:25',
    book:'Proverbs',
    category:'debuff',
    verseType:'wisdom',
    damage:0,
    effect:'debuff',
    difficulty:3,
    crossRefs:['prov26_24', 'prov26_26', 'prov26_27'],
    comboWith:['prov3_5', 'prov3_6'],
    desc:'The Word binds the enemy.',
  },
  {
    id:'prov26_26',
    text:'Hatred is covered by deceit.',
    reference:'Proverbs 26:26',
    book:'Proverbs',
    category:'debuff',
    verseType:'wisdom',
    damage:0,
    effect:'debuff',
    difficulty:3,
    crossRefs:['prov26_24', 'prov26_25', 'prov26_27'],
    comboWith:['prov3_5', 'prov3_6'],
    desc:'The Word binds the enemy.',
  },
  {
    id:'prov29_25',
    text:'Fear of man bringeth a snare.',
    reference:'Proverbs 29:25',
    book:'Proverbs',
    category:'debuff',
    verseType:'wisdom',
    damage:0,
    effect:'debuff',
    difficulty:2,
    crossRefs:['prov29_1'],
    comboWith:['prov3_5', 'prov3_6'],
    desc:'The Word binds the enemy.',
  },
  {
    id:'heb4_12',
    text:'Word of God sharper than sword.',
    reference:'Hebrews 4:12',
    book:'Hebrews',
    category:'debuff',
    verseType:'wisdom',
    damage:0,
    effect:'debuff',
    difficulty:3,
    crossRefs:['heb11_1', 'heb12_2'],
    comboWith:['heb11_1', 'prov3_5'],
    desc:'The Word binds the enemy.',
  },
  {
    id:'jam4_7',
    text:'Resist the devil, he flees.',
    reference:'James 4:7',
    book:'James',
    category:'debuff',
    verseType:'mercy',
    damage:0,
    effect:'debuff',
    difficulty:1,
    crossRefs:['jam5_16', 'jam1_5'],
    comboWith:['jam1_5', 'prov3_5'],
    desc:'The Word binds the enemy.',
  },
  {
    id:'jam5_16',
    text:'Fervent prayer availeth much.',
    reference:'James 5:16',
    book:'James',
    category:'debuff',
    verseType:'mercy',
    damage:0,
    effect:'debuff',
    difficulty:2,
    crossRefs:['jam4_7', 'jam1_5'],
    comboWith:['jam1_5', 'prov3_5'],
    desc:'The Word binds the enemy.',
  },
  {
    id:'cor2_10_4',
    text:'Weapons of warfare mighty in God.',
    reference:'2 Corinthians 10:4',
    book:'2 Corinthians',
    category:'debuff',
    verseType:'warfare',
    damage:0,
    effect:'debuff',
    difficulty:3,
    crossRefs:['cor2_10_5'],
    comboWith:['cor2_12_10', 'prov3_5'],
    desc:'The Word binds the enemy.',
  },
  {
    id:'cor2_10_5',
    text:'Casting down imaginations.',
    reference:'2 Corinthians 10:5',
    book:'2 Corinthians',
    category:'debuff',
    verseType:'warfare',
    damage:0,
    effect:'debuff',
    difficulty:3,
    crossRefs:['cor2_10_4'],
    comboWith:['cor2_12_10', 'prov3_5'],
    desc:'The Word binds the enemy.',
  },
  {
    id:'eph5_11',
    text:'No fellowship with unfruitful works.',
    reference:'Ephesians 5:11',
    book:'Ephesians',
    category:'debuff',
    verseType:'warfare',
    damage:0,
    effect:'debuff',
    difficulty:2,
    crossRefs:['eph6_11', 'eph6_12'],
    comboWith:['prov3_5', 'prov3_6'],
    desc:'The Word binds the enemy.',
  },
  {
    id:'prov6_16',
    text:'Six things the LORD hateth.',
    reference:'Proverbs 6:16',
    book:'Proverbs',
    category:'debuff',
    verseType:'wisdom',
    damage:0,
    effect:'debuff',
    difficulty:2,
    crossRefs:['prov6_17'],
    comboWith:['prov3_5', 'prov3_6'],
    desc:'The Word binds the enemy.',
  },
  {
    id:'prov6_17',
    text:'A proud look, a lying tongue.',
    reference:'Proverbs 6:17',
    book:'Proverbs',
    category:'debuff',
    verseType:'wisdom',
    damage:0,
    effect:'debuff',
    difficulty:2,
    crossRefs:['prov6_16'],
    comboWith:['prov3_5', 'prov3_6'],
    desc:'The Word binds the enemy.',
  },
  {
    id:'prov11_21',
    text:'The wicked shall not go unpunished.',
    reference:'Proverbs 11:21',
    book:'Proverbs',
    category:'debuff',
    verseType:'wisdom',
    damage:0,
    effect:'debuff',
    difficulty:2,
    crossRefs:['prov12_19', 'prov9_10'],
    comboWith:['prov3_5', 'prov3_6'],
    desc:'The Word binds the enemy.',
  },
  {
    id:'prov12_19',
    text:'A lying lip is but for a moment.',
    reference:'Proverbs 12:19',
    book:'Proverbs',
    category:'debuff',
    verseType:'wisdom',
    damage:0,
    effect:'debuff',
    difficulty:2,
    crossRefs:['prov11_21', 'prov13_5'],
    comboWith:['prov3_5', 'prov3_6'],
    desc:'The Word binds the enemy.',
  },
  {
    id:'prov13_5',
    text:'A wicked man is loathsome.',
    reference:'Proverbs 13:5',
    book:'Proverbs',
    category:'debuff',
    verseType:'wisdom',
    damage:0,
    effect:'debuff',
    difficulty:2,
    crossRefs:['prov12_19', 'prov15_1'],
    comboWith:['prov3_5', 'prov3_6'],
    desc:'The Word binds the enemy.',
  },
  {
    id:'prov16_5',
    text:'Proud in heart: abomination.',
    reference:'Proverbs 16:5',
    book:'Proverbs',
    category:'debuff',
    verseType:'wisdom',
    damage:0,
    effect:'debuff',
    difficulty:2,
    crossRefs:['prov16_3', 'prov16_24'],
    comboWith:['prov3_5', 'prov3_6'],
    desc:'The Word binds the enemy.',
  },
  {
    id:'prov19_5',
    text:'A false witness not unpunished.',
    reference:'Proverbs 19:5',
    book:'Proverbs',
    category:'debuff',
    verseType:'wisdom',
    damage:0,
    effect:'debuff',
    difficulty:2,
    crossRefs:['prov18_21', 'prov17_17'],
    comboWith:['prov3_5', 'prov3_6'],
    desc:'The Word binds the enemy.',
  },
  {
    id:'prov21_30',
    text:'No counsel against the LORD.',
    reference:'Proverbs 21:30',
    book:'Proverbs',
    category:'debuff',
    verseType:'wisdom',
    damage:0,
    effect:'debuff',
    difficulty:3,
    crossRefs:['prov19_5', 'prov18_21'],
    comboWith:['prov3_5', 'prov3_6'],
    desc:'The Word binds the enemy.',
  },
  {
    id:'prov24_24',
    text:'That calleth wicked men just.',
    reference:'Proverbs 24:24',
    book:'Proverbs',
    category:'debuff',
    verseType:'wisdom',
    damage:0,
    effect:'debuff',
    difficulty:3,
    crossRefs:['prov24_16'],
    comboWith:['prov3_5', 'prov3_6'],
    desc:'The Word binds the enemy.',
  },
  {
    id:'prov26_27',
    text:'Whoso digs a pit shall fall.',
    reference:'Proverbs 26:27',
    book:'Proverbs',
    category:'debuff',
    verseType:'wisdom',
    damage:0,
    effect:'debuff',
    difficulty:2,
    crossRefs:['prov26_24', 'prov26_25', 'prov26_26'],
    comboWith:['prov3_5', 'prov3_6'],
    desc:'The Word binds the enemy.',
  },
  {
    id:'prov28_9',
    text:'He that turns from the law.',
    reference:'Proverbs 28:9',
    book:'Proverbs',
    category:'debuff',
    verseType:'wisdom',
    damage:0,
    effect:'debuff',
    difficulty:2,
    crossRefs:['prov27_17', 'prov29_25'],
    comboWith:['prov3_5', 'prov3_6'],
    desc:'The Word binds the enemy.',
  },
  {
    id:'prov29_1',
    text:'Often reproved, yet hardens.',
    reference:'Proverbs 29:1',
    book:'Proverbs',
    category:'debuff',
    verseType:'wisdom',
    damage:0,
    effect:'debuff',
    difficulty:3,
    crossRefs:['prov29_25'],
    comboWith:['prov3_5', 'prov3_6'],
    desc:'The Word binds the enemy.',
  },
  {
    id:'isa8_10',
    text:'Take counsel: it comes to nought.',
    reference:'Isaiah 8:10',
    book:'Isaiah',
    category:'debuff',
    verseType:'warfare',
    damage:0,
    effect:'debuff',
    difficulty:3,
    crossRefs:['isa9_6', 'isa26_3'],
    comboWith:['prov3_5', 'prov3_6'],
    desc:'The Word binds the enemy.',
  },
  {
    id:'rev3_19',
    text:'As many as I love, I rebuke.',
    reference:'Revelation 3:19',
    book:'Revelation',
    category:'debuff',
    verseType:'fire',
    damage:0,
    effect:'debuff',
    difficulty:2,
    crossRefs:['rev3_20'],
    comboWith:['prov3_5', 'prov3_6'],
    desc:'The Word binds the enemy.',
  },
  {
    id:'jud1_9',
    text:'Michael disputed about the body.',
    reference:'Jude 1:9',
    book:'Jude',
    category:'debuff',
    verseType:'mercy',
    damage:0,
    effect:'stun',
    difficulty:3,
    crossRefs:['jam4_7', 'rev20_10'],
    comboWith:['prov3_5', 'prov3_6'],
    desc:'The Word binds the enemy.',
  },
  {
    id:'tim2_25',
    text:'In meekness instruct opposers.',
    reference:'2 Timothy 2:25',
    book:'2 Timothy',
    category:'debuff',
    verseType:'mercy',
    damage:0,
    effect:'debuff',
    difficulty:3,
    crossRefs:['tim2_3', 'tim2_4'],
    comboWith:['tim1_7', 'prov3_5'],
    desc:'The Word binds the enemy.',
  },
  {
    id:'tit2_12',
    text:'Denying ungodliness and lusts.',
    reference:'Titus 2:12',
    book:'Titus',
    category:'debuff',
    verseType:'mercy',
    damage:0,
    effect:'debuff',
    difficulty:2,
    crossRefs:['jam5_16', 'prov15_1'],
    comboWith:['prov3_5', 'prov3_6'],
    desc:'The Word binds the enemy.',
  },
  {
    id:'ps119_104',
    text:'I hate every false way.',
    reference:'Psalm 119:104',
    book:'Psalms',
    category:'debuff',
    verseType:'praise',
    damage:0,
    effect:'debuff',
    difficulty:2,
    crossRefs:['ps118_24', 'ps121_7'],
    comboWith:['prov3_5', 'prov3_6'],
    desc:'The Word binds the enemy.',
  },
  {
    id:'jn1_4_4',
    text:'Greater is he that is in you.',
    reference:'1 John 4:4',
    book:'1 John',
    category:'ultimate',
    verseType:'mercy',
    damage:70,
    effect:'execute',
    difficulty:1,
    crossRefs:['jn4_4'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'Greater He, greater you.',
  },
  {
    id:'jn4_4',
    text:'Ye are of God, overcome them.',
    reference:'1 John 4:4',
    book:'1 John',
    category:'ultimate',
    verseType:'mercy',
    damage:65,
    effect:'execute',
    difficulty:1,
    crossRefs:['jn1_4_4'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The fullness of the Word unleashed.',
  },
  {
    id:'isa54_17',
    text:'No weapon formed prospers.',
    reference:'Isaiah 54:17',
    book:'Isaiah',
    category:'ultimate',
    verseType:'warfare',
    damage:80,
    effect:'execute',
    difficulty:1,
    crossRefs:['isa59_19', 'isa46_4'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'No weapon in any age prevails.',
  },
  {
    id:'isa43_2',
    text:'When thou passest through waters.',
    reference:'Isaiah 43:2',
    book:'Isaiah',
    category:'ultimate',
    verseType:'warfare',
    damage:75,
    effect:'aoe',
    difficulty:1,
    crossRefs:['isa41_10', 'isa40_31'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The fullness of the Word unleashed.',
  },
  {
    id:'phil4_13',
    text:'I can do all things through Christ.',
    reference:'Philippians 4:13',
    book:'Philippians',
    category:'ultimate',
    verseType:'mercy',
    damage:70,
    effect:'buff',
    difficulty:1,
    crossRefs:['phil4_19'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The signature cry of the overcomer.',
  },
  {
    id:'rom8_31',
    text:'If God be for us, none against.',
    reference:'Romans 8:31',
    book:'Romans',
    category:'ultimate',
    verseType:'mercy',
    damage:75,
    effect:'buff',
    difficulty:1,
    crossRefs:['rom8_28', 'rom8_37', 'rom8_38', 'rom8_39'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The unanswerable premise.',
  },
  {
    id:'eph6_10',
    text:'Be strong in the Lord.',
    reference:'Ephesians 6:10',
    book:'Ephesians',
    category:'ultimate',
    verseType:'warfare',
    damage:60,
    effect:'armor',
    difficulty:1,
    crossRefs:['eph6_11', 'eph6_12', 'eph6_13', 'eph6_14', 'eph6_15', 'eph6_16', 'eph6_17', 'eph6_18'],
    comboWith:['eph6_11', 'eph6_12'],
    desc:'Root of all armor: His strength.',
  },
  {
    id:'rev5_5',
    text:'Lion of Judah hath prevailed.',
    reference:'Revelation 5:5',
    book:'Revelation',
    category:'ultimate',
    verseType:'fire',
    damage:90,
    effect:'aoe',
    difficulty:1,
    crossRefs:['rev3_20', 'rev3_19'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The Lion breaks every seal.',
  },
  {
    id:'deut28_7',
    text:'Lord causes enemies to be smitten.',
    reference:'Deuteronomy 28:7',
    book:'Deuteronomy',
    category:'ultimate',
    verseType:'warfare',
    damage:70,
    effect:'execute',
    difficulty:2,
    crossRefs:['isa54_17', 'dan3_17'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The fullness of the Word unleashed.',
  },
  {
    id:'num6_24',
    text:'The LORD bless thee, keep thee.',
    reference:'Numbers 6:24',
    book:'Numbers',
    category:'ultimate',
    verseType:'mercy',
    damage:55,
    effect:'heal_15',
    difficulty:1,
    crossRefs:['num6_25', 'num6_26'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The fullness of the Word unleashed.',
  },
  {
    id:'num6_25',
    text:'Make his face shine on thee.',
    reference:'Numbers 6:25',
    book:'Numbers',
    category:'ultimate',
    verseType:'mercy',
    damage:55,
    effect:'heal_10',
    difficulty:1,
    crossRefs:['num6_24', 'num6_26'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The fullness of the Word unleashed.',
  },
  {
    id:'num6_26',
    text:'LORD lift his countenance on thee.',
    reference:'Numbers 6:26',
    book:'Numbers',
    category:'ultimate',
    verseType:'mercy',
    damage:55,
    effect:'heal_15',
    difficulty:1,
    crossRefs:['num6_24', 'num6_25'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The fullness of the Word unleashed.',
  },
  {
    id:'cor2_12_9',
    text:'My grace is sufficient: power in weakness.',
    reference:'2 Corinthians 12:9',
    book:'2 Corinthians',
    category:'ultimate',
    verseType:'mercy',
    damage:65,
    effect:'buff',
    difficulty:1,
    crossRefs:['cor2_12_10'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The fullness of the Word unleashed.',
  },
  {
    id:'pet1_7',
    text:'Trial of faith precious as gold.',
    reference:'1 Peter 1:7',
    book:'1 Peter',
    category:'ultimate',
    verseType:'mercy',
    damage:60,
    effect:'buff',
    difficulty:2,
    crossRefs:['pet1_5'],
    comboWith:['pet1_5', 'ps23_4'],
    desc:'The fullness of the Word unleashed.',
  },
  {
    id:'rev22_13',
    text:'I am Alpha and Omega, first/last.',
    reference:'Revelation 22:13',
    book:'Revelation',
    category:'ultimate',
    verseType:'fire',
    damage:85,
    effect:'execute',
    difficulty:2,
    crossRefs:['rev22_20'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The fullness of the Word unleashed.',
  },
  {
    id:'rev1_8',
    text:'I am Alpha and Omega, saith Lord.',
    reference:'Revelation 1:8',
    book:'Revelation',
    category:'ultimate',
    verseType:'fire',
    damage:80,
    effect:'aoe',
    difficulty:2,
    crossRefs:['rev1_17', 'rev1_18'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The fullness of the Word unleashed.',
  },
  {
    id:'rev11_15',
    text:'Kingdoms of world become the Lord\'s.',
    reference:'Revelation 11:15',
    book:'Revelation',
    category:'ultimate',
    verseType:'fire',
    damage:75,
    effect:'aoe',
    difficulty:3,
    crossRefs:['rev12_11', 'rev5_5'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The fullness of the Word unleashed.',
  },
  {
    id:'isa9_6',
    text:'A child is born: Prince of Peace.',
    reference:'Isaiah 9:6',
    book:'Isaiah',
    category:'ultimate',
    verseType:'warfare',
    damage:80,
    effect:'aoe',
    difficulty:2,
    crossRefs:['isa8_10', 'isa26_3'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The fullness of the Word unleashed.',
  },
  {
    id:'isa40_28',
    text:'The everlasting God fainteth not.',
    reference:'Isaiah 40:28',
    book:'Isaiah',
    category:'ultimate',
    verseType:'warfare',
    damage:70,
    effect:'buff',
    difficulty:3,
    crossRefs:['isa40_31'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The fullness of the Word unleashed.',
  },
  {
    id:'isa46_4',
    text:'I have made, I will bear.',
    reference:'Isaiah 46:4',
    book:'Isaiah',
    category:'ultimate',
    verseType:'warfare',
    damage:65,
    effect:'heal_15',
    difficulty:2,
    crossRefs:['isa43_2', 'isa41_10'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The fullness of the Word unleashed.',
  },
  {
    id:'jer29_11',
    text:'Thoughts of peace, not of evil.',
    reference:'Jeremiah 29:11',
    book:'Jeremiah',
    category:'ultimate',
    verseType:'mercy',
    damage:60,
    effect:'heal_10',
    difficulty:2,
    crossRefs:['rom8_28', 'phil4_19'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The fullness of the Word unleashed.',
  },
  {
    id:'ps91_11',
    text:'He gives angels charge over thee.',
    reference:'Psalm 91:11',
    book:'Psalms',
    category:'ultimate',
    verseType:'praise',
    damage:60,
    effect:'shield',
    difficulty:1,
    crossRefs:['ps91_1', 'ps91_2', 'ps91_3', 'ps91_4', 'ps91_5', 'ps91_6', 'ps91_12'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The fullness of the Word unleashed.',
  },
  {
    id:'ps91_12',
    text:'They shall bear thee up.',
    reference:'Psalm 91:12',
    book:'Psalms',
    category:'ultimate',
    verseType:'praise',
    damage:55,
    effect:'shield',
    difficulty:1,
    crossRefs:['ps91_1', 'ps91_2', 'ps91_3', 'ps91_4', 'ps91_5', 'ps91_6', 'ps91_11'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The fullness of the Word unleashed.',
  },
  {
    id:'dan3_17',
    text:'Our God is able to deliver.',
    reference:'Daniel 3:17',
    book:'Daniel',
    category:'ultimate',
    verseType:'warfare',
    damage:70,
    effect:'execute',
    difficulty:3,
    crossRefs:['dan3_18'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The fullness of the Word unleashed.',
  },
  {
    id:'dan3_18',
    text:'We will not serve thy gods.',
    reference:'Daniel 3:18',
    book:'Daniel',
    category:'ultimate',
    verseType:'warfare',
    damage:65,
    effect:'buff',
    difficulty:3,
    crossRefs:['dan3_17'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The fullness of the Word unleashed.',
  },
  {
    id:'tim4_7',
    text:'I have fought a good fight.',
    reference:'2 Timothy 4:7',
    book:'2 Timothy',
    category:'ultimate',
    verseType:'mercy',
    damage:60,
    effect:'buff',
    difficulty:2,
    crossRefs:['tim4_8'],
    comboWith:['tim2_3', 'tim2_4'],
    desc:'The fullness of the Word unleashed.',
  },
  {
    id:'tim4_8',
    text:'A crown of righteousness laid up.',
    reference:'2 Timothy 4:8',
    book:'2 Timothy',
    category:'ultimate',
    verseType:'mercy',
    damage:60,
    effect:'buff',
    difficulty:2,
    crossRefs:['tim4_7'],
    comboWith:['tim2_3', 'tim2_4'],
    desc:'The fullness of the Word unleashed.',
  },
  {
    id:'heb12_2',
    text:'Author and finisher of faith.',
    reference:'Hebrews 12:2',
    book:'Hebrews',
    category:'ultimate',
    verseType:'mercy',
    damage:65,
    effect:'buff',
    difficulty:2,
    crossRefs:['heb11_1', 'heb4_12'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The fullness of the Word unleashed.',
  },
  {
    id:'rom16_20',
    text:'God bruises Satan under feet.',
    reference:'Romans 16:20',
    book:'Romans',
    category:'ultimate',
    verseType:'mercy',
    damage:70,
    effect:'execute',
    difficulty:2,
    crossRefs:['rom15_13', 'rom12_2'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The fullness of the Word unleashed.',
  },
  {
    id:'ps103_20',
    text:'Bless the LORD, ye his angels.',
    reference:'Psalm 103:20',
    book:'Psalms',
    category:'ultimate',
    verseType:'praise',
    damage:55,
    effect:'aoe',
    difficulty:2,
    crossRefs:['ps91_1', 'ps91_2'],
    comboWith:['ps23_4', 'ps46_2'],
    desc:'The fullness of the Word unleashed.',
  },
];


// ── Lookups ────────────────────────────────────────────
function getVerseById(id){
  for (let i=0;i<BIBLE_VERSES.length;i++) if (BIBLE_VERSES[i].id===id) return BIBLE_VERSES[i];
  return null;
}
function getVersesByCategory(cat){
  return BIBLE_VERSES.filter(v => v.category===cat);
}
function getVersesByType(type){
  return BIBLE_VERSES.filter(v => v.verseType===type);
}
function getCrossRefs(verseId){
  const v = getVerseById(verseId);
  if (!v) return [];
  return v.crossRefs.map(getVerseById).filter(Boolean);
}
function getComboPartners(verseId){
  const v = getVerseById(verseId);
  if (!v) return [];
  return v.comboWith.map(getVerseById).filter(Boolean);
}
function getBibleStats(discoveredIds){
  const disc = discoveredIds || [];
  const inSet = id => disc.indexOf(id) >= 0;
  const cats = ['attack','defense','buff','debuff','ultimate'];
  const byCategory = {};
  for (const c of cats){
    const all = getVersesByCategory(c);
    byCategory[c] = { total: all.length, discovered: all.filter(v => inSet(v.id)).length };
  }
  const total = BIBLE_VERSES.length;
  const discovered = BIBLE_VERSES.filter(v => inSet(v.id)).length;
  const pct = total ? Math.round((discovered/total)*100) : 0;
  return { total, discovered, pct, byCategory };
}

// Categories + types enumerations (handy for UI)
const BIBLE_CATEGORIES = ['attack','defense','buff','debuff','ultimate'];
const BIBLE_TYPES = ['praise','wisdom','warfare','fire','mercy'];

// Icon glyph per category (drawn by bible-ui)
const BIBLE_CAT_ICON = {
  attack:'+', defense:'O', buff:'^', debuff:'x', ultimate:'*'
};
const BIBLE_CAT_COLOR = {
  attack:'#cc3333', defense:'#3344aa', buff:'#00aa44', debuff:'#7733aa', ultimate:'#ffd700'
};
